package com.example.winkit

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.ui.Modifier
import com.example.winkit.ui.navigation.AppNavigation
import com.example.winkit.ui.theme.WinkItTheme // Ensure this matches your actual theme import

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            WinkItTheme { // This is auto-generated by Android Studio
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colorScheme.background
                ) {
                    // Boot up the navigation!
                    AppNavigation()
                }
            }
        }
    }
}
